// dutchGeo.ts
// Offline dataset for auto-detecting Dutch geographic names from MeshCore channel names.
// Covers all 12 provinces, all 25 veiligheidsregio's, and 100+ major municipalities.

export interface DutchGeoEntry {
  name: string;
  aliases: string[];
  type: 'province' | 'municipality' | 'region';
  province: string;
  provinceCode: string;
  veiligheidsregio: string;
  veiligheidsregio_code: string;
  scopes: string[];
  country: string;
  notes?: string;
}

// ---------------------------------------------------------------------------
// PROVINCES
// ---------------------------------------------------------------------------

const PROVINCES: DutchGeoEntry[] = [
  {
    name: 'Noord-Holland',
    aliases: ['noordholland', 'nh', 'north holland', 'northholland'],
    type: 'province',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Noord-Holland Noord',
    veiligheidsregio_code: 'vr-vrnhn',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
  },
  {
    name: 'Zuid-Holland',
    aliases: ['zuidholland', 'zh', 'south holland', 'southholland'],
    type: 'province',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh'],
    country: 'Netherlands',
  },
  {
    name: 'Utrecht',
    aliases: ['ut', 'utrecht province'],
    type: 'province',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut'],
    country: 'Netherlands',
  },
  {
    name: 'Noord-Brabant',
    aliases: ['noordbrabant', 'nb', 'brabant', 'north brabant', 'northbrabant'],
    type: 'province',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb'],
    country: 'Netherlands',
  },
  {
    name: 'Gelderland',
    aliases: ['ge', 'gld', 'gelderland province'],
    type: 'province',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge'],
    country: 'Netherlands',
  },
  {
    name: 'Overijssel',
    aliases: ['ov', 'overijssel province'],
    type: 'province',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'IJsselland',
    veiligheidsregio_code: 'vr-vrij',
    scopes: ['nl', 'nl-ov'],
    country: 'Netherlands',
  },
  {
    name: 'Groningen',
    aliases: ['gr', 'gro', 'groningen province'],
    type: 'province',
    province: 'Groningen',
    provinceCode: 'gr',
    veiligheidsregio: 'Groningen',
    veiligheidsregio_code: 'vr-hvdg',
    scopes: ['nl', 'nl-gr'],
    country: 'Netherlands',
  },
  {
    name: 'Friesland',
    aliases: ['fr', 'fryslan', 'fryslân', 'frisia', 'frisian', 'friesland province'],
    type: 'province',
    province: 'Friesland',
    provinceCode: 'fr',
    veiligheidsregio: 'Friesland',
    veiligheidsregio_code: 'vr-vrf',
    scopes: ['nl', 'nl-fr'],
    country: 'Netherlands',
  },
  {
    name: 'Drenthe',
    aliases: ['dr', 'drenthe province'],
    type: 'province',
    province: 'Drenthe',
    provinceCode: 'dr',
    veiligheidsregio: 'Drenthe',
    veiligheidsregio_code: 'vr-vrd',
    scopes: ['nl', 'nl-dr'],
    country: 'Netherlands',
  },
  {
    name: 'Flevoland',
    aliases: ['fl', 'flevoland province'],
    type: 'province',
    province: 'Flevoland',
    provinceCode: 'fl',
    veiligheidsregio: 'Flevoland',
    veiligheidsregio_code: 'vr-vrfl',
    scopes: ['nl', 'nl-fl'],
    country: 'Netherlands',
  },
  {
    name: 'Zeeland',
    aliases: ['ze', 'zeeland province', 'zealand'],
    type: 'province',
    province: 'Zeeland',
    provinceCode: 'ze',
    veiligheidsregio: 'Zeeland',
    veiligheidsregio_code: 'vr-vrz',
    scopes: ['nl', 'nl-ze'],
    country: 'Netherlands',
  },
  {
    name: 'Limburg',
    aliases: ['li', 'lb', 'limburg province'],
    type: 'province',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Zuid-Limburg',
    veiligheidsregio_code: 'vr-vrzl',
    scopes: ['nl', 'nl-li'],
    country: 'Netherlands',
  },
];

// ---------------------------------------------------------------------------
// VEILIGHEIDSREGIO'S (safety regions)
// ---------------------------------------------------------------------------

const VEILIGHEIDSREGIOS: DutchGeoEntry[] = [
  {
    name: 'Amsterdam-Amstelland',
    aliases: ['amsterdamamstelland', 'vramsterdamamstelland'],
    type: 'region',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Amsterdam-Amstelland',
    veiligheidsregio_code: 'vr-vraa',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
  },
  {
    name: 'Kennemerland',
    aliases: ['vrkennemerland'],
    type: 'region',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Kennemerland',
    veiligheidsregio_code: 'vr-vrk',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
  },
  {
    name: 'Noord-Holland Noord',
    aliases: ['noordhollandnoord', 'nhn', 'vrnoordhollandnoord'],
    type: 'region',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Noord-Holland Noord',
    veiligheidsregio_code: 'vr-vrnhn',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
  },
  {
    name: 'Zaanstreek-Waterland',
    aliases: ['zaanstreekwaterland', 'vrzaanstreekwaterland'],
    type: 'region',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Zaanstreek-Waterland',
    veiligheidsregio_code: 'vr-vrzw',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
  },
  {
    name: 'Gooi en Vechtstreek',
    aliases: ['gooienvechtstreek', 'gooi', 'vechtstreek', 'vrgooivechtstreek'],
    type: 'region',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Gooi en Vechtstreek',
    veiligheidsregio_code: 'vr-vrgv',
    scopes: ['nl', 'nl-nh'],
    country: 'Netherlands',
    notes: 'Spans Noord-Holland and Utrecht',
  },
  {
    name: 'Rotterdam-Rijnmond',
    aliases: ['rotterdamrijnmond', 'rijnmond', 'vrrijnmond'],
    type: 'region',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh'],
    country: 'Netherlands',
  },
  {
    name: 'Hollands Midden',
    aliases: ['hollandsmidden', 'vrhollandsmidden'],
    type: 'region',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Hollands Midden',
    veiligheidsregio_code: 'vr-vrhm',
    scopes: ['nl', 'nl-zh'],
    country: 'Netherlands',
  },
  {
    name: 'Haaglanden',
    aliases: ['vrhaaglanden'],
    type: 'region',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh'],
    country: 'Netherlands',
  },
  {
    name: 'Zuid-Holland Zuid',
    aliases: ['zuidhollandzuid', 'zhzuid', 'vrzhzuid'],
    type: 'region',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh'],
    country: 'Netherlands',
  },
  {
    name: 'Utrecht (veiligheidsregio)',
    aliases: ['vrutrecht'],
    type: 'region',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut'],
    country: 'Netherlands',
  },
  {
    name: 'Flevoland (veiligheidsregio)',
    aliases: ['vrflevoland'],
    type: 'region',
    province: 'Flevoland',
    provinceCode: 'fl',
    veiligheidsregio: 'Flevoland',
    veiligheidsregio_code: 'vr-vrfl',
    scopes: ['nl', 'nl-fl'],
    country: 'Netherlands',
  },
  {
    name: 'IJsselland',
    aliases: ['ijsselland', 'yselland', 'vrijsselland'],
    type: 'region',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'IJsselland',
    veiligheidsregio_code: 'vr-vrij',
    scopes: ['nl', 'nl-ov'],
    country: 'Netherlands',
  },
  {
    name: 'Twente',
    aliases: ['vrtwente'],
    type: 'region',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'Twente',
    veiligheidsregio_code: 'vr-vrt',
    scopes: ['nl', 'nl-ov'],
    country: 'Netherlands',
  },
  {
    name: 'Noord-Oost Gelderland',
    aliases: ['noordoostgelderland', 'noog', 'vrnoog'],
    type: 'region',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Noord-Oost Gelderland',
    veiligheidsregio_code: 'vr-vnog',
    scopes: ['nl', 'nl-ge'],
    country: 'Netherlands',
  },
  {
    name: 'Gelderland-Midden',
    aliases: ['gelderlandmidden', 'vrgelderlandmidden'],
    type: 'region',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge'],
    country: 'Netherlands',
  },
  {
    name: 'Gelderland-Zuid',
    aliases: ['gelderlandzuid', 'vrgelderlandzuid'],
    type: 'region',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Zuid',
    veiligheidsregio_code: 'vr-vrgz',
    scopes: ['nl', 'nl-ge'],
    country: 'Netherlands',
  },
  {
    name: 'Brabant-Noord',
    aliases: ['brabannoord', 'vrbrabantnoord'],
    type: 'region',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Noord',
    veiligheidsregio_code: 'vr-vrbn',
    scopes: ['nl', 'nl-nb'],
    country: 'Netherlands',
  },
  {
    name: 'Brabant-Zuidoost',
    aliases: ['brabantzuidoost', 'vrbrabanzuidoost'],
    type: 'region',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Zuidoost',
    veiligheidsregio_code: 'vr-vrbzo',
    scopes: ['nl', 'nl-nb'],
    country: 'Netherlands',
  },
  {
    name: 'Midden- en West-Brabant',
    aliases: ['middenwestbrabant', 'middenenwestbrabant', 'vrmiddenwestbrabant'],
    type: 'region',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb'],
    country: 'Netherlands',
  },
  {
    name: 'Zeeland (veiligheidsregio)',
    aliases: ['vrzeeland'],
    type: 'region',
    province: 'Zeeland',
    provinceCode: 'ze',
    veiligheidsregio: 'Zeeland',
    veiligheidsregio_code: 'vr-vrz',
    scopes: ['nl', 'nl-ze'],
    country: 'Netherlands',
  },
  {
    name: 'Limburg-Noord',
    aliases: ['limburnoord', 'vrlimburgnoord'],
    type: 'region',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Limburg-Noord',
    veiligheidsregio_code: 'vr-vrln',
    scopes: ['nl', 'nl-li'],
    country: 'Netherlands',
  },
  {
    name: 'Zuid-Limburg',
    aliases: ['zuidlimburg', 'vrzuidlimburg'],
    type: 'region',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Zuid-Limburg',
    veiligheidsregio_code: 'vr-vrzl',
    scopes: ['nl', 'nl-li'],
    country: 'Netherlands',
  },
  {
    name: 'Friesland (veiligheidsregio)',
    aliases: ['vrfriesland', 'vrfryslân', 'vrfryslan'],
    type: 'region',
    province: 'Friesland',
    provinceCode: 'fr',
    veiligheidsregio: 'Friesland',
    veiligheidsregio_code: 'vr-vrf',
    scopes: ['nl', 'nl-fr'],
    country: 'Netherlands',
  },
  {
    name: 'Drenthe (veiligheidsregio)',
    aliases: ['vrdrenthe'],
    type: 'region',
    province: 'Drenthe',
    provinceCode: 'dr',
    veiligheidsregio: 'Drenthe',
    veiligheidsregio_code: 'vr-vrd',
    scopes: ['nl', 'nl-dr'],
    country: 'Netherlands',
  },
  {
    name: 'Groningen (veiligheidsregio)',
    aliases: ['vrgroningen'],
    type: 'region',
    province: 'Groningen',
    provinceCode: 'gr',
    veiligheidsregio: 'Groningen',
    veiligheidsregio_code: 'vr-hvdg',
    scopes: ['nl', 'nl-gr'],
    country: 'Netherlands',
  },
];

// ---------------------------------------------------------------------------
// MUNICIPALITIES
// ---------------------------------------------------------------------------

const MUNICIPALITIES: DutchGeoEntry[] = [
  // --- Noord-Holland ---
  {
    name: 'Amsterdam',
    aliases: ['adam', 'ams', 'amsterdam city'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Amsterdam-Amstelland',
    veiligheidsregio_code: 'vr-vraa',
    scopes: ['nl', 'nl-nh', 'nl-nh-ams'],
    country: 'Netherlands',
  },
  {
    name: 'Haarlem',
    aliases: ['hrm', 'haarlem city'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Kennemerland',
    veiligheidsregio_code: 'vr-vrk',
    scopes: ['nl', 'nl-nh', 'nl-nh-hrl'],
    country: 'Netherlands',
  },
  {
    name: 'Alkmaar',
    aliases: ['alk'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Noord-Holland Noord',
    veiligheidsregio_code: 'vr-vrnhn',
    scopes: ['nl', 'nl-nh', 'nl-nh-alk'],
    country: 'Netherlands',
  },
  {
    name: 'Zaandam',
    aliases: ['zaanstad', 'zaan'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Zaanstreek-Waterland',
    veiligheidsregio_code: 'vr-vrzw',
    scopes: ['nl', 'nl-nh', 'nl-nh-zdm'],
    country: 'Netherlands',
  },
  {
    name: 'Amstelveen',
    aliases: ['amstelveen city'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Amsterdam-Amstelland',
    veiligheidsregio_code: 'vr-vraa',
    scopes: ['nl', 'nl-nh', 'nl-nh-amstelveen'],
    country: 'Netherlands',
  },
  {
    name: 'Purmerend',
    aliases: ['purm'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Zaanstreek-Waterland',
    veiligheidsregio_code: 'vr-vrzw',
    scopes: ['nl', 'nl-nh', 'nl-nh-purmerend'],
    country: 'Netherlands',
  },
  {
    name: 'Hoorn',
    aliases: ['hoorn city'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Noord-Holland Noord',
    veiligheidsregio_code: 'vr-vrnhn',
    scopes: ['nl', 'nl-nh', 'nl-nh-hoorn'],
    country: 'Netherlands',
  },
  {
    name: 'Hilversum',
    aliases: ['hilv', 'hilversum city'],
    type: 'municipality',
    province: 'Noord-Holland',
    provinceCode: 'nh',
    veiligheidsregio: 'Gooi en Vechtstreek',
    veiligheidsregio_code: 'vr-vrgv',
    scopes: ['nl', 'nl-nh', 'nl-nh-hlv'],
    country: 'Netherlands',
  },
  // --- Zuid-Holland ---
  {
    name: 'Rotterdam',
    aliases: ['rot', 'r-dam', 'rdam'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-rtm'],
    country: 'Netherlands',
  },
  {
    name: 'Den Haag',
    aliases: ['denhaag', 'sgravenhage', 'thehague', 'the hague', 'gravenhage', 'haag'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-dhh'],
    country: 'Netherlands',
    notes: "Officially 's-Gravenhage",
  },
  {
    name: 'Leiden',
    aliases: ['leiden city', 'ley'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Hollands Midden',
    veiligheidsregio_code: 'vr-vrhm',
    scopes: ['nl', 'nl-zh', 'nl-zh-ldn'],
    country: 'Netherlands',
  },
  {
    name: 'Dordrecht',
    aliases: ['dort', 'dordt'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-ddr'],
    country: 'Netherlands',
  },
  {
    name: 'Zoetermeer',
    aliases: ['zoet', 'zoetermeer city'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-zoetermeer'],
    country: 'Netherlands',
  },
  {
    name: 'Delft',
    aliases: ['delft city'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-dlf'],
    country: 'Netherlands',
  },
  {
    name: 'Westland',
    aliases: ['westland municipality'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-westland'],
    country: 'Netherlands',
  },
  {
    name: 'Gouda',
    aliases: ['gouda city'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Hollands Midden',
    veiligheidsregio_code: 'vr-vrhm',
    scopes: ['nl', 'nl-zh', 'nl-zh-gda'],
    country: 'Netherlands',
  },
  {
    name: 'Schiedam',
    aliases: ['schied'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-schiedam'],
    country: 'Netherlands',
  },
  {
    name: 'Vlaardingen',
    aliases: ['vlaard'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-vld'],
    country: 'Netherlands',
  },
  {
    name: 'Ridderkerk',
    aliases: ['ridder'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-ridderkerk'],
    country: 'Netherlands',
  },
  {
    name: 'Capelle aan den IJssel',
    aliases: ['capelleaandenijssel', 'capelle', 'capelleijssel'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-cap'],
    country: 'Netherlands',
  },
  {
    name: 'Nissewaard',
    aliases: ['spijkenisse', 'spijk'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-nissewaard'],
    country: 'Netherlands',
    notes: 'Formerly Spijkenisse',
  },
  {
    name: 'Lansingerland',
    aliases: ['lansing', 'lansingerland municipality'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-lansingerland'],
    country: 'Netherlands',
  },
  {
    name: 'Barendrecht',
    aliases: ['barend'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-barendrecht'],
    country: 'Netherlands',
  },
  {
    name: 'Papendrecht',
    aliases: ['pap'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-papendrecht'],
    country: 'Netherlands',
  },
  {
    name: 'Sliedrecht',
    aliases: ['slied'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-sliedrecht'],
    country: 'Netherlands',
  },
  {
    name: 'Gorinchem',
    aliases: ['gorkum', 'gorcum'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-gorinchem'],
    country: 'Netherlands',
  },
  {
    name: 'Alblasserdam',
    aliases: ['alblas'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-alblasserdam'],
    country: 'Netherlands',
  },
  {
    name: 'Hendrik-Ido-Ambacht',
    aliases: ['hendrikidoambacht', 'hendrikido', 'hia'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Zuid-Holland Zuid',
    veiligheidsregio_code: 'vr-vrzhz',
    scopes: ['nl', 'nl-zh', 'nl-zh-hendrikidoambacht'],
    country: 'Netherlands',
  },
  {
    name: 'Albrandswaard',
    aliases: ['albrands'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Rotterdam-Rijnmond',
    veiligheidsregio_code: 'vr-vrr',
    scopes: ['nl', 'nl-zh', 'nl-zh-albrandswaard'],
    country: 'Netherlands',
  },
  {
    name: 'Pijnacker-Nootdorp',
    aliases: ['pijnackernootdorp', 'pijnacker', 'nootdorp'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-pijnackernootdorp'],
    country: 'Netherlands',
  },
  {
    name: 'Midden-Delfland',
    aliases: ['middendelfland', 'middendelf'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-middendelfland'],
    country: 'Netherlands',
  },
  {
    name: 'Naaldwijk',
    aliases: ['naaldwijk city', 'maasdijk', 'wateringen', 'monster'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Haaglanden',
    veiligheidsregio_code: 'vr-vrh',
    scopes: ['nl', 'nl-zh', 'nl-zh-westland'],
    country: 'Netherlands',
    notes: 'Part of Westland municipality; Naaldwijk is the main town',
  },
  {
    name: 'Alphen aan den Rijn',
    aliases: ['alphenaarijnijn', 'alphen', 'alphenaandenrijn'],
    type: 'municipality',
    province: 'Zuid-Holland',
    provinceCode: 'zh',
    veiligheidsregio: 'Hollands Midden',
    veiligheidsregio_code: 'vr-vrhm',
    scopes: ['nl', 'nl-zh', 'nl-zh-alphenaandenrijn'],
    country: 'Netherlands',
  },
  // --- Utrecht ---
  {
    name: 'Utrecht (city)',
    aliases: ['utrecht', 'utrechtstadl', 'utrechtstad'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-utrecht'],
    country: 'Netherlands',
  },
  {
    name: 'Amersfoort',
    aliases: ['amersfoort city', 'amersf'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-ame'],
    country: 'Netherlands',
  },
  {
    name: 'Woerden',
    aliases: ['woerden city'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-woerden'],
    country: 'Netherlands',
  },
  {
    name: 'IJsselstein',
    aliases: ['ijsselstein', 'yselstein'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-ijs'],
    country: 'Netherlands',
  },
  {
    name: 'Nieuwegein',
    aliases: ['nieuwegein city'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-nieuwegein'],
    country: 'Netherlands',
  },
  {
    name: 'Veenendaal',
    aliases: ['veen', 'veenendaal city'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-veenendaal'],
    country: 'Netherlands',
  },
  {
    name: 'Houten',
    aliases: ['houten city'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-htn'],
    country: 'Netherlands',
  },
  {
    name: 'Zeist',
    aliases: ['zeist city'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-zst'],
    country: 'Netherlands',
  },
  {
    name: 'De Bilt',
    aliases: ['debilt', 'bilt'],
    type: 'municipality',
    province: 'Utrecht',
    provinceCode: 'ut',
    veiligheidsregio: 'Utrecht',
    veiligheidsregio_code: 'vr-vru',
    scopes: ['nl', 'nl-ut', 'nl-ut-debilt'],
    country: 'Netherlands',
  },
  // --- Noord-Brabant ---
  {
    name: 'Eindhoven',
    aliases: ['ein', 'eind'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Zuidoost',
    veiligheidsregio_code: 'vr-vrbzo',
    scopes: ['nl', 'nl-nb', 'nl-nb-ehv'],
    country: 'Netherlands',
  },
  {
    name: 'Tilburg',
    aliases: ['tilb'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb', 'nl-nb-til'],
    country: 'Netherlands',
  },
  {
    name: 'Breda',
    aliases: ['bred'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb', 'nl-nb-breda'],
    country: 'Netherlands',
  },
  {
    name: "'s-Hertogenbosch",
    aliases: ['denbosch', 'hertogenbosch', 'bois le duc', 'shertogenbosch', 'bossche'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Noord',
    veiligheidsregio_code: 'vr-vrbn',
    scopes: ['nl', 'nl-nb', 'nl-nb-hertogenbosch'],
    country: 'Netherlands',
    notes: 'Also known as Den Bosch',
  },
  {
    name: 'Helmond',
    aliases: ['helm'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Zuidoost',
    veiligheidsregio_code: 'vr-vrbzo',
    scopes: ['nl', 'nl-nb', 'nl-nb-helmond'],
    country: 'Netherlands',
  },
  {
    name: 'Roosendaal',
    aliases: ['roosen'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb', 'nl-nb-roosendaal'],
    country: 'Netherlands',
  },
  {
    name: 'Bergen op Zoom',
    aliases: ['bergenopzoom', 'bergopzoom', 'boz'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Midden- en West-Brabant',
    veiligheidsregio_code: 'vr-vrmwb',
    scopes: ['nl', 'nl-nb', 'nl-nb-bergenopzoom'],
    country: 'Netherlands',
  },
  {
    name: 'Oss',
    aliases: ['oss city'],
    type: 'municipality',
    province: 'Noord-Brabant',
    provinceCode: 'nb',
    veiligheidsregio: 'Brabant-Noord',
    veiligheidsregio_code: 'vr-vrbn',
    scopes: ['nl', 'nl-nb', 'nl-nb-oss'],
    country: 'Netherlands',
  },
  {
    name: 'Weert',
    aliases: ['weert city'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Limburg-Noord',
    veiligheidsregio_code: 'vr-vrln',
    scopes: ['nl', 'nl-li', 'nl-li-weert'],
    country: 'Netherlands',
    notes: 'Sometimes listed under Noord-Brabant border area',
  },
  // --- Gelderland ---
  {
    name: 'Nijmegen',
    aliases: ['nimwegen', 'nijm'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Zuid',
    veiligheidsregio_code: 'vr-vrgz',
    scopes: ['nl', 'nl-ge', 'nl-ge-nij'],
    country: 'Netherlands',
  },
  {
    name: 'Arnhem',
    aliases: ['arnh'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge', 'nl-ge-arn'],
    country: 'Netherlands',
  },
  {
    name: 'Apeldoorn',
    aliases: ['apeld'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Noord-Oost Gelderland',
    veiligheidsregio_code: 'vr-vnog',
    scopes: ['nl', 'nl-ge', 'nl-ge-apd'],
    country: 'Netherlands',
  },
  {
    name: 'Ede',
    aliases: ['ede city'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge', 'nl-ge-ede'],
    country: 'Netherlands',
  },
  {
    name: 'Doetinchem',
    aliases: ['doet'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Noord-Oost Gelderland',
    veiligheidsregio_code: 'vr-vnog',
    scopes: ['nl', 'nl-ge', 'nl-ge-doetinchem'],
    country: 'Netherlands',
  },
  {
    name: 'Nijkerk',
    aliases: ['nijkerk city'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge', 'nl-ge-nijkerk'],
    country: 'Netherlands',
  },
  {
    name: 'Harderwijk',
    aliases: ['harder', 'hdw'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Noord-Oost Gelderland',
    veiligheidsregio_code: 'vr-vnog',
    scopes: ['nl', 'nl-ge', 'nl-ge-harderwijk'],
    country: 'Netherlands',
  },
  {
    name: 'Wageningen',
    aliases: ['wag'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Midden',
    veiligheidsregio_code: 'vr-vggm',
    scopes: ['nl', 'nl-ge', 'nl-ge-wageningen'],
    country: 'Netherlands',
  },
  {
    name: 'Tiel',
    aliases: ['tiel city'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Zuid',
    veiligheidsregio_code: 'vr-vrgz',
    scopes: ['nl', 'nl-ge', 'nl-ge-tiel'],
    country: 'Netherlands',
  },
  {
    name: 'Culemborg',
    aliases: ['culem'],
    type: 'municipality',
    province: 'Gelderland',
    provinceCode: 'ge',
    veiligheidsregio: 'Gelderland-Zuid',
    veiligheidsregio_code: 'vr-vrgz',
    scopes: ['nl', 'nl-ge', 'nl-ge-culemborg'],
    country: 'Netherlands',
  },
  // --- Overijssel ---
  {
    name: 'Enschede',
    aliases: ['enschede city', 'ensch'],
    type: 'municipality',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'Twente',
    veiligheidsregio_code: 'vr-vrt',
    scopes: ['nl', 'nl-ov', 'nl-ov-ens'],
    country: 'Netherlands',
  },
  {
    name: 'Zwolle',
    aliases: ['zwol'],
    type: 'municipality',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'IJsselland',
    veiligheidsregio_code: 'vr-vrij',
    scopes: ['nl', 'nl-ov', 'nl-ov-zwl'],
    country: 'Netherlands',
  },
  {
    name: 'Deventer',
    aliases: ['dev'],
    type: 'municipality',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'IJsselland',
    veiligheidsregio_code: 'vr-vrij',
    scopes: ['nl', 'nl-ov', 'nl-ov-dev'],
    country: 'Netherlands',
  },
  {
    name: 'Almelo',
    aliases: ['alm', 'almelo city'],
    type: 'municipality',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'Twente',
    veiligheidsregio_code: 'vr-vrt',
    scopes: ['nl', 'nl-ov', 'nl-ov-alm'],
    country: 'Netherlands',
  },
  {
    name: 'Hengelo',
    aliases: ['heng'],
    type: 'municipality',
    province: 'Overijssel',
    provinceCode: 'ov',
    veiligheidsregio: 'Twente',
    veiligheidsregio_code: 'vr-vrt',
    scopes: ['nl', 'nl-ov', 'nl-ov-hgl'],
    country: 'Netherlands',
  },
  // --- Groningen ---
  {
    name: 'Groningen (city)',
    aliases: ['groningen', 'gron', 'stad groningen'],
    type: 'municipality',
    province: 'Groningen',
    provinceCode: 'gr',
    veiligheidsregio: 'Groningen',
    veiligheidsregio_code: 'vr-hvdg',
    scopes: ['nl', 'nl-gr', 'nl-gr-grq'],
    country: 'Netherlands',
  },
  // --- Friesland ---
  {
    name: 'Leeuwarden',
    aliases: ['leeuwar', 'ljouwert'],
    type: 'municipality',
    province: 'Friesland',
    provinceCode: 'fr',
    veiligheidsregio: 'Friesland',
    veiligheidsregio_code: 'vr-vrf',
    scopes: ['nl', 'nl-fr', 'nl-fr-lwr'],
    country: 'Netherlands',
  },
  // --- Drenthe ---
  {
    name: 'Emmen',
    aliases: ['emmen city'],
    type: 'municipality',
    province: 'Drenthe',
    provinceCode: 'dr',
    veiligheidsregio: 'Drenthe',
    veiligheidsregio_code: 'vr-vrd',
    scopes: ['nl', 'nl-dr', 'nl-dr-emm'],
    country: 'Netherlands',
  },
  // --- Flevoland ---
  {
    name: 'Almere',
    aliases: ['alm', 'almere city'],
    type: 'municipality',
    province: 'Flevoland',
    provinceCode: 'fl',
    veiligheidsregio: 'Flevoland',
    veiligheidsregio_code: 'vr-vrfl',
    scopes: ['nl', 'nl-fl', 'nl-fl-alm'],
    country: 'Netherlands',
  },
  {
    name: 'Lelystad',
    aliases: ['lely'],
    type: 'municipality',
    province: 'Flevoland',
    provinceCode: 'fl',
    veiligheidsregio: 'Flevoland',
    veiligheidsregio_code: 'vr-vrfl',
    scopes: ['nl', 'nl-fl', 'nl-fl-lelystad'],
    country: 'Netherlands',
  },
  // --- Zeeland ---
  {
    name: 'Middelburg',
    aliases: ['midd'],
    type: 'municipality',
    province: 'Zeeland',
    provinceCode: 'ze',
    veiligheidsregio: 'Zeeland',
    veiligheidsregio_code: 'vr-vrz',
    scopes: ['nl', 'nl-ze', 'nl-ze-mid'],
    country: 'Netherlands',
  },
  {
    name: 'Vlissingen',
    aliases: ['vliss', 'flushing'],
    type: 'municipality',
    province: 'Zeeland',
    provinceCode: 'ze',
    veiligheidsregio: 'Zeeland',
    veiligheidsregio_code: 'vr-vrz',
    scopes: ['nl', 'nl-ze', 'nl-ze-vls'],
    country: 'Netherlands',
  },
  {
    name: 'Terneuzen',
    aliases: ['terneuzen city'],
    type: 'municipality',
    province: 'Zeeland',
    provinceCode: 'ze',
    veiligheidsregio: 'Zeeland',
    veiligheidsregio_code: 'vr-vrz',
    scopes: ['nl', 'nl-ze', 'nl-ze-terneuzen'],
    country: 'Netherlands',
  },
  // --- Limburg ---
  {
    name: 'Maastricht',
    aliases: ['maast', 'maastr'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Zuid-Limburg',
    veiligheidsregio_code: 'vr-vrzl',
    scopes: ['nl', 'nl-li', 'nl-li-maa'],
    country: 'Netherlands',
  },
  {
    name: 'Venlo',
    aliases: ['venlo city'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Limburg-Noord',
    veiligheidsregio_code: 'vr-vrln',
    scopes: ['nl', 'nl-li', 'nl-li-vnl'],
    country: 'Netherlands',
  },
  {
    name: 'Heerlen',
    aliases: ['heerl'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Zuid-Limburg',
    veiligheidsregio_code: 'vr-vrzl',
    scopes: ['nl', 'nl-li', 'nl-li-heerlen'],
    country: 'Netherlands',
  },
  {
    name: 'Sittard',
    aliases: ['sittard city', 'sittardgeleen', 'sittardgeleen'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Zuid-Limburg',
    veiligheidsregio_code: 'vr-vrzl',
    scopes: ['nl', 'nl-li', 'nl-li-sittard'],
    country: 'Netherlands',
  },
  {
    name: 'Roermond',
    aliases: ['roerm'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Limburg-Noord',
    veiligheidsregio_code: 'vr-vrln',
    scopes: ['nl', 'nl-li', 'nl-li-roermond'],
    country: 'Netherlands',
  },
  {
    name: 'Venray',
    aliases: ['venray city'],
    type: 'municipality',
    province: 'Limburg',
    provinceCode: 'li',
    veiligheidsregio: 'Limburg-Noord',
    veiligheidsregio_code: 'vr-vrln',
    scopes: ['nl', 'nl-li', 'nl-li-venray'],
    country: 'Netherlands',
  },
];

// ---------------------------------------------------------------------------
// Full dataset export
// ---------------------------------------------------------------------------

export const DUTCH_GEO: DutchGeoEntry[] = [...PROVINCES, ...VEILIGHEIDSREGIOS, ...MUNICIPALITIES];

// ---------------------------------------------------------------------------
// Matching helper
// ---------------------------------------------------------------------------

/**
 * Normalize a string for comparison: lowercase, strip leading #,
 * remove spaces, hyphens, and underscores.
 */
function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/^#+/, '') // strip leading hash(es)
    .replace(/[\s\-_]/g, '') // remove spaces, hyphens, underscores
    .trim();
}

/**
 * Match a MeshCore channel name (e.g. "#amsterdam", "noord-holland", "rijnmond")
 * against the DUTCH_GEO dataset.
 *
 * Matching order:
 *  1. Exact match on normalized canonical name
 *  2. Exact match on any alias
 *
 * Returns the first matching entry or null.
 */
export function matchDutchChannel(channelName: string): DutchGeoEntry | null {
  const key = normalize(channelName);

  if (!key) return null;

  for (const entry of DUTCH_GEO) {
    if (normalize(entry.name) === key) return entry;
  }

  for (const entry of DUTCH_GEO) {
    for (const alias of entry.aliases) {
      if (normalize(alias) === key) return entry;
    }
  }

  return null;
}

// ---------------------------------------------------------------------------
// Auto-fill helper
// ---------------------------------------------------------------------------

export interface ChannelAutoFill {
  country: string;
  region: string;
  scopes: string[];
  notes: string;
  category: string;
  subcategory: string;
}

/**
 * Build an auto-fill object from a DutchGeoEntry, suitable for populating
 * a channel registry form.
 *
 * The veiligheidsregio is added to scopes with a "VR " prefix so it can be
 * styled distinctly (see isVeiligheidsregio below).
 */
export function buildAutoFillFromGeo(entry: DutchGeoEntry): ChannelAutoFill {
  const vrScope = entry.veiligheidsregio_code;
  const scopes = entry.scopes.includes(vrScope) ? entry.scopes : [...entry.scopes, vrScope];
  return {
    country: 'Netherlands',
    region: entry.province,
    scopes,
    notes: entry.notes ?? '',
    category: 'Regional',
    subcategory: entry.type === 'province' ? 'Province' : 'City',
  };
}

/**
 * Returns true if the given scope string is a Dutch veiligheidsregio.
 * These are stored as "vr-<slug>" in the scopes array (e.g. "vr-vrgz").
 * Used to render VR scopes with a distinct red/orange badge in the UI.
 */
export function isVeiligheidsregio(scope: string): boolean {
  return scope.startsWith('vr-');
}
